---
title: "nba rapm model"
author: "Matt Sheridan"
date: "2023-09-06"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(Matrix)
library(glmnet)
library(knitr)
library(dplyr)

teams <- c("Boston Celtics", "Philadelphia 76ers", "Brooklyn Nets", "Toronto Raptors")

possession_data <- read.csv('shift_aggregated_20212022.csv') %>% filter((timeofpos > 0) & (team1id %in% teams) & (team2id %in% teams))

od <- read.csv("https://raw.githubusercontent.com/rd11490/NBA_Tutorials/master/rapm/data/rapm_possessions.csv") %>% 
  filter(possessions != 0) %>% select(-X)

od

#player_data <- read.csv("https://raw.githubusercontent.com/rd11490/NBA_Tutorials/master/rapm/data/player_names.csv")


```



```{r}

get_players <- function(possesions) {
  
  possesions <- distinct(possesions)
  players <- unique(c(unique(possesions$team1player1),
                      unique(possesions$team1player2),
                      unique(possesions$team1player3),
                      unique(possesions$team1player4),
                      unique(possesions$team1player5),
                      unique(possesions$team2player1),
                      unique(possesions$team2player2),
                      unique(possesions$team2player3),
                      unique(possesions$team2player4),
                      unique(possesions$team2player5)))
  return(players)
  
}

players <- sort(get_players(possesions = possesion_data))

print(paste0("There are ", length(players), " unique players in the dataset."))

```


```{r}

possession_data <- possession_data %>% mutate(pdpsec = (team1_points - team2_points) / timeofpos) %>% as.matrix()

```


```{r}

make_matrix_rows <- function(lineup, players_in) {
  
  player1 <- lineup[1]
  player2 <- lineup[2]
  player3 <- lineup[3]
  player4 <- lineup[4]
  player5 <- lineup[5]
  player6 <- lineup[6]
  player7 <- lineup[7]
  player8 <- lineup[8]
  player9 <- lineup[9]
  player10 <- lineup[10]
  
  zeroRow <- rep(0, length(players_in))
  
  # OFFENSE #
  zeroRow[which(players_in == player1)] <- 1
  zeroRow[which(players_in == player2)] <- 1
  zeroRow[which(players_in == player3)] <- 1
  zeroRow[which(players_in == player4)] <- 1
  zeroRow[which(players_in == player5)] <- 1
  
  # DEFENSE #
  zeroRow[which(players_in == player6)] <- -1
  zeroRow[which(players_in == player7)] <- -1
  zeroRow[which(players_in == player8)] <- -1
  zeroRow[which(players_in == player9)] <- -1
  zeroRow[which(players_in == player10)] <- -1
  
  return(zeroRow)
  
}


pl_mat <- as.data.frame(apply(outer(as.matrix(possession_data[,2:6], ncol = 5), players, "==") - outer(as.matrix(possession_data[,8:12], ncol = 5), players, "=="), 3, rowSums))

colnames(pl_mat) <- players


player_matrix <- t(apply(possession_data[, c(2:6, 8:12)], 1, 
                         function(x) make_matrix_rows(lineup = x, players_in = players)))

player_matrix <- as(player_matrix, "dgCMatrix")

target <- possession_data$pdpsec
weights <- possession_data$timeofpos

print(dim(player_matrix))


X = Reduce("+", apply(possession_data[,2:6], 2, function(column) outer(column, players, "=="), simplify = F)) - Reduce("+", apply(possession_data[,8:12], 2, function(column) outer(column, players, "=="), simplify = F))

```


```{r}
options(scipen = 9999)
set.seed(143)
## this is a cross validated model to pick the lambda
cv_model <- glmnet::cv.glmnet(x = X, ##ncol = 1058
                           y = target,
                           alpha = 0, 
                           standardize = FALSE,
                           weights = weights)

lam <- cv_model$lambda.min ## best lambda

## this is the model refit using that lambda
coef_model <- glmnet::glmnet(x = player_matrix, 
                          y = target,
                          alpha = 0, 
                          standardize = FALSE,
                          lambda = lam,
                          weights = weights)

player_coefficients <- coef_model$beta ## length = 1058

o_rapm <- player_coefficients[1:length(players)]

d_rapm <- player_coefficients[length(players) + 1:length(players) * 2]

o_rapm_frame <- data.frame("player_id" = players,
                           "o_rapm" = o_rapm)

d_rapm_frame <- data.frame("player_id" = players,
                           "d_rapm" = d_rapm)

rapm <- left_join(o_rapm_frame, d_rapm_frame, by = "player_id") %>% 
#  left_join(player_data, by = c("player_id" = "playerId")) %>% 
  mutate(rapm = o_rapm + d_rapm) %>% 
  select(Player = player_id,
         RAPM = rapm,
         `O-RAPM` = o_rapm,
         `D-RAPM` = d_rapm) %>% 
  arrange(-`O-RAPM`)

kable(rapm[1:5, ] %>% 
          mutate(across(where(is.numeric), function(x) round(x, 5))), align = "c") 

```